
title: Ethnicity facts and figures style guide and templates

# Build settings
markdown: kramdown
theme: govuk-jekyll-theme
remote_theme: frankieroberto/govuk-jekyll-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
